apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: eqasim
spec:
  maxRetry: 1
  minAvailable: 1
  schedulerName: volcano
  queue: default
  tasks:
    - replicas: 1
      name: train
      template:
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: dkr-creds
          securityContext:
            runAsUser: 1000
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: nvidia.com/gpu.product
                        operator: In
                        values:
                          - NVIDIA-RTX-A6000
                          - NVIDIA-GeForce-RTX-3090

          containers:
            - name: runner
              imagePullPolicy: Always
              image: mu00120825.eng.monash.edu.au:5021/eqasim:latest
              command:
                [
                  "uv",
                  "run",
                  "-m",
                  "synpp",
                  "/eqasim/config.yml",
                  "--working-directory",
                  "/eqasim/cache",
                  "--data_path",
                  "/eqasim/data",
                  "--output_path",
                  "/mnt/slow2/eqasim-output",
                ]
              workingDir: /eqasim

              env:
                - name: WANDB_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: wandb
                      key: api-key
                - name: WANDB_CACHE_DIR
                  value: /home/user

              resources:
                requests:
                  memory: 48Gi
                  cpu: 6000m
                limits:
                  memory: 64Gi
                  cpu: 10000m
              volumeMounts:
                - name: storage
                  mountPath: /mnt/storage
                - name: slow
                  mountPath: /mnt/slow
                - name: slow2
                  mountPath: /mnt/slow2
                - mountPath: /dev/shm
                  name: dshm
          volumes:
            - name: storage
              flexVolume:
                driver: fstab/cifs
                fsType: cifs
                secretRef:
                  name: smb-creds
                options:
                  networkPath: //130.194.128.238/fast
                  mountOptions: dir_mode=0777,file_mode=0777,noperm
            - name: slow2
              flexVolume:
                driver: fstab/cifs
                fsType: cifs
                secretRef:
                  name: smb-creds
                options:
                  networkPath: //130.194.128.238/slow
                  mountOptions: dir_mode=0777,file_mode=0777,noperm
            - name: slow
              nfs:
                server: 130.194.128.238
                path: /mnt/fast/more-users/bryce-rhys

            - name: dshm
              emptyDir:
                medium: Memory