version: '3.8'

services:
  service:
      network_mode: "host"
      build:
        dockerfile: Dockerfile
        context: .
      image: melbourne-baseline:latest

      tty: true
      stdin_open: true
      privileged: true
      restart: unless-stopped

      environment:
        - DISPLAY=:0
        - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
